### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ozanoner** [reederz/node-red-contrib-coap#12]
Hi guys,
This project seems a bit old. many dependency errors. do you have any plan to update this node in the future? I appreciate if you can :)
Best regards

**Comment by ozanoner** [comment]
hey @reederz, thanks for reply! 
> node --version
v8.10.0
> npm --version
3.5.2
> node-red
1 Feb 10:08:08 - [info] Node-RED version: v0.19.5
1 Feb 10:08:08 - [info] Node.js  version: v8.10.0
1 Feb 10:08:08 - [info] Linux 4.18.5-041805-generic x64 LE

Actually, I am testing OpenThread, and I need a coap-server on border router. You know, node-red is a good choice for such things. I installed it on an rpi, then used this contrib for coap server functionality to get data from the network. All went well for now, thanks for it! 
Now, I need coap-secure, but it is not supported in this version of the contrib. It would be great if you can add that feature too. I'm struggling with Californium for the purpose. 
Best regards

**Comment by ozanoner** [comment]
Yes. Many thanks!

**Comment by reederz** [comment]
I'm on a hectic travel schedule now - not gonna be able to look into this before end of March. Happy to accept a pull request.

**Comment by ozanoner** [comment]
I wish I could, but I don't feel I can implement this since I'm not a js dev.
