### ISSUE TITLE
Push latest to npmjs.org

### ISSUE THREAD

**Issue by homeautomaton** [reederz/node-red-contrib-coap#16]
I would like to contribute to this project, but I see that the latest version on npmjs.org is from 2016, and the last work done here is 2017. I'd rather test my changes with the later version, though I've been working solely with what I installed from npm. There are significant changes in `coap-request.js` right in the area where I'd like to make a change.

Are any of the contributors here still active?

**Comment by reederz** [comment]
@homeautomaton new maintainer is @JKRhb . I transferred the repo to him. If you still want to contribute, you can talk to him.
